# Juan Valdez ♥

El café tiene: 
- Aroma
- Cuerpo
- Acidez
- Sabor
- Composición

Se tienen 100 muestras de café que serán analizadas por 4 expertos

In [87]:
# importación de librerías
import numpy as np

from sklearn import preprocessing

# Selector de características
from sklearn.datasets import samples_generator # Generamos un toyset
from sklearn.feature_selection import SelectKBest, f_regression 
from sklearn.pipeline import Pipeline
from sklearn import neighbors


In [89]:
# importación de los datos
expertos_ruta = 'expertos.txt'
X_train = np.loadtxt(expertos_ruta, delimiter=',')

test_ruta = 'test.txt'
X_test = np.loadtxt(test_ruta, delimiter=',')

puntuaciones_ruta = 'puntuaciones.txt'
y = np.loadtxt(puntuaciones_ruta, delimiter=',')

## Escalamiento:
Nos permite medir con la misma regla todas las características:

$$\frac{\mathbf{X}-min(\mathbf{X})}{max(\mathbf{X}) - min(\mathbf{X})},$$

In [91]:
escalador = preprocessing.MinMaxScaler(feature_range=(0, 1))
   

## Selector de características

In [95]:
selector = SelectKBest(f_regression, k=4)

## Algoritmo para clasificador k-NN

In [118]:
clasificador = neighbors.KNeighborsClassifier(6, weights = 'distance')
clasificador.fit(X_train, y[:,2])

modelo_nn = NearestNeighbors(n_neighbors= k, algorithm='ball_tree').fit(X_train)
distancias, indices = modelo_nn.kneighbors(X_test)


print('Los vecinos mas cercanos')

for rank, index in enumerate(indices[0][:k], start=1):
    print(str(rank) + '----->', X_train[index])

NameError: name 'NearestNeighbors' is not defined

## Creación de Pipeline

In [110]:
# Creamos el pipeline
pipeline = Pipeline([('escalamiento', escalador),('selector', selector),('clasficador',clasificador)])

## Entrenamos el Pipeline

In [114]:
pipeline.fit(X_train,y[:,2])



[[  7.  13.  12.  11.  12.]
 [  8.  11.  12.   8.   9.]
 [ 15.  12.   7.   5.  13.]
 [  9.  26.   6.  11.   4.]
 [  7.   9.   8.  10.   5.]
 [ 10.   8.   9.  13.  14.]
 [  6.   6.  21.  13.  15.]
 [ 12.  12.  16.   8.   9.]
 [  8.   7.   4.   9.  10.]
 [ 10.   8.   4.  14.  11.]
 [ 11.  10.   7.  13.  12.]
 [  5.   6.  19.   6.  14.]
 [ 11.  10.   6.  11.   9.]
 [  9.  11.  14.   8.  10.]
 [  7.   6.  20.   8.  11.]
 [  6.   6.   5.   9.   9.]
 [  4.   6.  16.  11.  11.]
 [ 12.  16.  11.   8.  11.]
 [ 13.   8.  16.   9.  10.]
 [ 14.  15.  13.  15.   8.]]
[ 1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  0.  1.]
