# Aprendizaje de máquina
Se divida en dos grandes áreas:
1. **Aprendizaje supervisado**: Se entrena un clasificador para identificar la etiqueta de un elemento nuevo. Las entradas para este modelo son: $\mathbf{X}$ la matriz de datos de dimension $n\times p$, donde $n$ es el numero de observaciones y $p$ es el numero de caracteristicas, y el conjunto de etiquetas $C=[c_1, c_2, \ldots, c_k]$, donde $k$ es el numero de clases
2. **Aprendizaje no supervisado**: Se intenta agrupar el conjunto de datos, de tal forma que la separción entre los grupos sea la más conveniente. En este caso la entrada va a estar dado solo por la matriz de datos $\mathbf{X}$, definida por


$$\mathbf{X} = \left[\begin{array}{cccc}
x_{11} & x_{12} & \ldots & x_{1p}\\
x_{21} & x_{22} & \ldots & x_{2p}\\ 
\vdots& &\ldots &\vdots \\
x_{n1} & x_{n2} & \ldots & x_{np}\\ 
\end{array}\right]$$

De forma generla, un modelo de ML tiene las siguientes etapas:

1. *Adquisición de datos*
2. *Acondicionamiento de los datos, tambien llamado preprocesamientos (filtrado y remoción de artefactos)*
3. *Caracterización*
4. ***Preprocesamiento de las caracteristicas***
5. *Reducción de dimensión*
6. ***Aplicación del modelo ML***
7. ***Analisis de resultado***

## Aprendizaje Supervisado
Con el fin de aplicar un modelo supervisado para la clasificación de datos, es necesario iniciar con la carga o adquisición de los datos,en nuestro caso será una matriz  $\mathbf{X}$  artificial:

$$\mathbf{X} = \left[\begin{array}{ccc}
5.1&-2.0&3.3\\
-1.2&7.8&-6.1 \\
3.9&0.4&2.1\\
7.3&-9.9&-4.5 \\
\end{array}\right]$$


In [8]:
import numpy as np

X = np.array([[5.1,-2.9,3.3],[-1.2,7.8,-6.1], [3.9,0.4,2.1],[7.3,-9.9,-4.5]])

print(X)

[[ 5.1 -2.9  3.3]
 [-1.2  7.8 -6.1]
 [ 3.9  0.4  2.1]
 [ 7.3 -9.9 -4.5]]


## Preprocesamiento de la matriz de datos
Dar uniformidad a las características con el fin de no sesgar el clasificador. Hay diferentes tipos de preprocesamiento entre los que se encuentran

1. Binarización 
2. Remoción de media
3. Escalamiento
4. Normalización

### 1. Binarización 
Convertir las caracteristicas en variables booleanas. Se debe fijar un umbral $\gamma$ para la binarización de los datos

In [2]:
def binarizacion(X, gamma) :
    filas = np.shape(X)[0]
    columnas = np.shape(X)[1]
    
    for i in range(filas) :
        for j in range(columnas) :
            X[i][j] = 1 if X[i][j] >= gamma else 0
    return X

In [3]:
gamma = float(input('Ingrese el valor de gamma'))
datos_binarizados = binarizacion(X,gamma)

print(datos_binarizados)

Ingrese el valor de gamma2.1
[[ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]
 [ 1.  0.  0.]]


### 2. Remoción de la media
Eliminar la tendencia de los datos. La operación que se realiza sobre la matriz de datos es la siguiente: 

$$\frac{\mathbf{X}-\mathbf{\hat{X}}}{\sigma_{\mathbf{X}}},$$

donde $\mathbf{\hat{X}}$ es la media y ${\sigma_{\mathbf{X}}}$ es la desviación 

In [4]:
def remocion(X):
    X = X - X.mean(axis=0)
    X = X/X.std(axis=0)
    
    return X

In [5]:
datos_centralizados = remocion(X)
media = datos_centralizados.mean(axis=0)
print('La media de las caracteristicas es', media)
desviacion = datos_centralizados.std(axis=0)
print('La desviacion de las caracteristicas es', desviacion)

La media de las caracteristicas es [  5.55111512e-17  -5.55111512e-17   0.00000000e+00]
La desviacion de las caracteristicas es [ 1.  1.  1.]


### 2. Escalamiento
Medir con la misma *regla* todas las caracteristicas a todas las caracteristicas,para ello se realiza la siguiente operacion:


$$\frac{\mathbf{X}-min(\mathbf{X})}{max(\mathbf{X}) - min(\mathbf{X})},$$


In [9]:
def escalamiento(X):
    X = X - X.min(axis=0)
    X = X/(X.max(axis=0) - X.min(axis=0))
    
    return X

In [11]:
datos_escalados = escalamiento(X)
print(datos_escalados)

[[ 0.74117647  0.39548023  1.        ]
 [ 0.          1.          0.        ]
 [ 0.6         0.5819209   0.87234043]
 [ 1.          0.          0.17021277]]
